export default function generateProseColors (
  theme: (path: string) => string,
  name: string,
) {
  return {
    '--tw-prose-body': theme(`colors.${name}[800]`),
    '--tw-prose-headings': theme(`colors.${name}[900]`),
    '--tw-prose-lead': theme(`colors.${name}[700]`),
    '--tw-prose-links': theme(`colors.${name}[900]`),
    '--tw-prose-bold': theme(`colors.${name}[900]`),
    '--tw-prose-counters': theme(`colors.${name}[600]`),
    '--tw-prose-bullets': theme(`colors.${name}[400]`),
    '--tw-prose-hr': theme(`colors.${name}[300]`),
    '--tw-prose-quotes': theme(`colors.${name}[900]`),
    '--tw-prose-quote-borders': theme(`colors.${name}[300]`),
    '--tw-prose-captions': theme(`colors.${name}[700]`),
    '--tw-prose-code': theme(`colors.${name}[900]`),
    '--tw-prose-pre-code': theme(`colors.${name}[100]`),
    '--tw-prose-pre-bg': theme(`colors.${name}[900]`),
    '--tw-prose-th-borders': theme(`colors.${name}[300]`),
    '--tw-prose-td-borders': theme(`colors.${name}[200]`),
    '--tw-prose-invert-body': theme(`colors.${name}[200]`),
    '--tw-prose-invert-headings': theme('colors.${name}[50]'),
    '--tw-prose-invert-lead': theme(`colors.${name}[300]`),
    '--tw-prose-invert-links': theme('colors.${name}[50]'),
    '--tw-prose-invert-bold': theme('colors.${name}[50]'),
    '--tw-prose-invert-counters': theme(`colors.${name}[400]`),
    '--tw-prose-invert-bullets': theme(`colors.${name}[600]`),
    '--tw-prose-invert-hr': theme(`colors.${name}[700]`),
    '--tw-prose-invert-quotes': theme(`colors.${name}[100]`),
    '--tw-prose-invert-quote-borders': theme(`colors.${name}[700]`),
    '--tw-prose-invert-captions': theme(`colors.${name}[400]`),
    '--tw-prose-invert-code': theme('colors.${name}[50]'),
    '--tw-prose-invert-pre-code': theme(`colors.${name}[300]`),
    '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
    '--tw-prose-invert-th-borders': theme(`colors.${name}[600]`),
    '--tw-prose-invert-td-borders': theme(`colors.${name}[700]`),
  }
}
