import environ

env = environ.Env()

GOOGLE_CLIENT_ID = env.str('GOOGLE_CLIENT_ID')
GOOGLE_SECRET = env.str('GOOGLE_SECRET')
GOOGLE_CALLBACK_URL = env.str('GOOGLE_CALLBACK_URL')

REDDIT_CLIENT_ID = env.str('REDDIT_CLIENT_ID')
REDDIT_SECRET = env.str('REDDIT_SECRET')
REDDIT_CALLBACK_URL = env.str('REDDIT_CALLBACK_URL')

GITHUB_CLIENT_ID = env.str('GITHUB_CLIENT_ID')
GITHUB_SECRET = env.str('GITHUB_SECRET')
GITHUB_CALLBACK_URL = env.str('GITHUB_CALLBACK_URL')